spring:
  application:
    name: api-gateway
  profiles:
    active: native
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      mvc:
        routes:
          - id: lesson-service
            uri: lb://lesson-service
            predicates:
              - Path=/lesson/**
          - id: student-service
            uri: lb://student-service
            predicates:
              - Path=/student/**

server:
  port: 8088


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  tracing:
    sampling:
      probability: 1.0